### ISSUE TITLE
Training time

### ISSUE THREAD

**Issue by tgangwani** [miyosuda/unreal#10]
Hi, 
The figures in the results section plot rewards vs time-steps during training (for seekavoid_arena and static_maze). How much host time (average) does each time-step take?

**Comment by miyosuda** [comment]
In my environment (GTX1080Ti and Core i7 6700), step speed for 'nav_maze_static_01' is 354 steps per second. (Tested with 8 parallel environments.) So 1M step takes 47 minutes. You can speed it up with more threads.
