### ISSUE TITLE
always display "Map loaded: 'nav_maze_static_01"

### ISSUE THREAD

**Issue by deepmeng** [miyosuda/unreal#13]
Hello, there always display "Map loaded: 'nav_maze_static_01", like this:

Map loaded: 'nav_maze_static_01'
Map loaded: 'nav_maze_static_01'
Map loaded: 'nav_maze_static_01'
Map loaded: 'nav_maze_static_01'
Map loaded: 'nav_maze_static_01'
Map loaded: 'nav_maze_static_01'
Map loaded: 'nav_maze_static_01'
Map loaded: 'nav_maze_static_01'
Map loaded: 'nav_maze_static_01'
Map loaded: 'nav_maze_static_01'
Map loaded: 'nav_maze_static_01'
Map loaded: 'nav_maze_static_01'
Map loaded: 'nav_maze_static_01'
Map loaded: 'nav_maze_static_01'
Map loaded: 'nav_maze_static_01'
Map loaded: 'nav_maze_static_01'
Map loaded: 'nav_maze_static_01'
Map loaded: 'nav_maze_static_01'
Map loaded: 'nav_maze_static_01'
Map loaded: 'nav_maze_static_01'
Map loaded: 'nav_maze_static_01'
Map loaded: 'nav_maze_static_01'
Map loaded: 'nav_maze_static_01'
Map loaded: 'nav_maze_static_01'
Map loaded: 'nav_maze_static_01'
Map loaded: 'nav_maze_static_01'
Map loaded: 'nav_maze_static_01'
Map loaded: 'nav_maze_static_01'
Map loaded: 'nav_maze_static_01'
Map loaded: 'nav_maze_static_01'
Map loaded: 'nav_maze_static_01'
Map loaded: 'nav_maze_static_01'
Map loaded: 'nav_maze_static_01'
Map loaded: 'nav_maze_static_01'
Map loaded: 'nav_maze_static_01'
Map loaded: 'nav_maze_static_01'
Map loaded: 'nav_maze_static_01'
Map loaded: 'nav_maze_static_01'
Map loaded: 'nav_maze_static_01'
Map loaded: 'nav_maze_static_01'
Map loaded: 'nav_maze_static_01'
Map loaded: 'nav_maze_static_01'
Map loaded: 'nav_maze_static_01'
Map loaded: 'nav_maze_static_01'
Map loaded: 'nav_maze_static_01'
Map loaded: 'nav_maze_static_01'
Map loaded: 'nav_maze_static_01'
Map loaded: 'nav_maze_static_01'
Map loaded: 'nav_maze_static_01'
Map loaded: 'nav_maze_static_01'
Map loaded: 'nav_maze_static_01'
Map loaded: 'nav_maze_static_01'
Map loaded: 'nav_maze_static_01'
Map loaded: 'nav_maze_static_01'
Map loaded: 'nav_maze_static_01'
Map loaded: 'nav_maze_static_01'
Map loaded: 'nav_maze_static_01'
Map loaded: 'nav_maze_static_01'
Map loaded: 'nav_maze_static_01'
Map loaded: 'nav_maze_static_01'
Map loaded: 'nav_maze_static_01'
Map loaded: 'nav_maze_static_01'
Map loaded: 'nav_maze_static_01'
Map loaded: 'nav_maze_static_01'
Map loaded: 'nav_maze_static_01'
Map loaded: 'nav_maze_static_01'
Map loaded: 'nav_maze_static_01'
Map loaded: 'nav_maze_static_01'
Map loaded: 'nav_maze_static_01'
Map loaded: 'nav_maze_static_01'
Map loaded: 'nav_maze_static_01'
Map loaded: 'nav_maze_static_01'
Map loaded: 'nav_maze_static_01'
Map loaded: 'nav_maze_static_01'
Map loaded: 'nav_maze_static_01'
Map loaded: 'nav_maze_static_01'
Map loaded: 'nav_maze_static_01'
Map loaded: 'nav_maze_static_01'
Map loaded: 'nav_maze_static_01'

so I want to know is it working well?

**Comment by miyosuda** [comment]
DeepMind lab environment reloads map data every time it reaches terminal state. (When reaching warp point.)

And then lab outputs these "Map loaded: 'nav_maze_static_01'" log internally. So it is normal to see these output logs.

**Comment by deepmeng** [comment]
@miyosuda  OK! Thanks!
