### ISSUE TITLE
Replicating inputs for VR and PC

### ISSUE THREAD

**Issue by pisiiki** [miyosuda/unreal#18]
Hello Miyosuda, I have observed that you are replicating the input of the base network for PC and VR. Replicating the conv layers and reusing kernels/pars. Are you sure this is required? To my understanding TF should be able to compute PC/VR by just reusing self.base_rnn_outputs. It should only process the required operations to get the requested data.

Regards and thanks for sharing your code.

**Comment by miyosuda** [comment]
Ah, That's right. I'll refactor it. Thanks.
