### ISSUE TITLE
How to plot the reward diagram?

### ISSUE THREAD

**Issue by etienne87** [miyosuda/unreal#4]
When i type : 

> tensorboard --logdir=./tmp/unreal_log

nothing shows up in "Scalar" Section. Can you describe in the README.md how to do it?

edit : nevermind. There is a "score" section.

**Comment by kkhetarpal** [comment]
Hi @etienne87 Could you please explain how do you plot the reward/score ? I did not find the "Score" section and I am new to Tensorflow as well. 

So far, I was able to set the code and ran it for 8M steps. I want to save the logs and plot scores to be my baseline. Any suggestions are of great help.
Thanks

**Comment by kkhetarpal** [comment]
Never mind, figured out. Had some issues with tensorboard and tensorflow paths.
