### ISSUE TITLE
use deepmind lab as a simple python module?

### ISSUE THREAD

**Issue by nina124** [miyosuda/unreal#6]
Sorry that I do not know much about the bazel.
If I want to use deepmind lab, do I have to run `bazel run //unreal:train --define headless=osmesa` ?
Is it possible that simply run `python train.py`
How do you debug with the deepmind_lab(with `bazel run xxx`)?
I ran `bazel run //unreal:train --define headless=osmesa`, but perhaps due to the tensroflow 1.0 upgrade, some errors appear, even after I adjusted the code to tf1.0
Also, thank you for sharing the code!

**Comment by miyosuda** [comment]
> How do you debug with the deepmind_lab

To debug after training, please run this command.

     bazel run //unreal:display --define headless=osmesa

> Is it possible that simply run python train.py

It seems a bit compilicated to run python directly using deepmind lab.
There was a discussion about this.

https://github.com/deepmind/lab/issues/37

>  but perhaps due to the tensroflow 1.0 

Sorry for inconvenience. I'm going to merge this tf1.0 upgrading pull request soon after I prepare tf1.0 environment.

https://github.com/miyosuda/unreal/pull/5

**Comment by miyosuda** [comment]
I merged Tensorflow 1.0 PR to master. Please try master branch.
