### ISSUE TITLE
Shouldn't A3C updates already happen before filling the replay buffer?

### ISSUE THREAD

**Issue by endymion64** [miyosuda/unreal#7]
First of all, great work @miyosuda !

I studied your project and the DeepMind [paper](https://arxiv.org/pdf/1611.05397.pdf), but as far as I understood the paper, I think the base A3C algorithm should already start updating the base A3C part of the network from the start. After a while, when the replay buffer is filled, the auxiliary tasks also begin to be trained.

Is my assumption correct?

**Comment by miyosuda** [comment]
Thank you for suggesting.
It will be ideal to train A3C before replay buffer is filled as you suggest.
However the replay buffer of UNREAL is relatively small (only 2000 frames), so I'm afraid there won't be so much difference even if we train before filling replay buffer.
